// Database schema (docs/SPEC.md, section 4, plus docs/DECISIONES.md).
// Column names are snake_case in the database: the Drizzle client and
// drizzle-kit both use `casing: "snake_case"`.
import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import {
  CALENDAR_EVENT_TYPES,
  CALENDAR_STATUSES,
  PIECE_STATUSES,
  type PieceStatus,
} from "@/domain/statuses";

const id = () => uuid().primaryKey().defaultRandom();
const instant = () => timestamp({ withTimezone: true });
const timestamps = () => ({
  createdAt: instant().notNull().defaultNow(),
  updatedAt: instant()
    .notNull()
    .defaultNow()
    .$onUpdate(() => sql`now()`),
});

// ---------------------------------------------------------------------------
// Better Auth: the core schema of better-auth 1.7 with plural model names
// (`usePlural`), ids generated by Postgres and rate limits in the database.

export const users = pgTable("users", {
  id: id(),
  name: text().notNull(),
  email: text().notNull().unique(),
  emailVerified: boolean().notNull().default(false),
  image: text(),
  ...timestamps(),
});

export const sessions = pgTable(
  "sessions",
  {
    id: id(),
    expiresAt: instant().notNull(),
    token: text().notNull().unique(),
    ipAddress: text(),
    userAgent: text(),
    userId: uuid()
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    ...timestamps(),
  },
  (t) => [index("sessions_user_id_idx").on(t.userId)],
);

export const accounts = pgTable(
  "accounts",
  {
    id: id(),
    accountId: text().notNull(),
    providerId: text().notNull(),
    userId: uuid()
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: instant(),
    refreshTokenExpiresAt: instant(),
    scope: text(),
    password: text(),
    ...timestamps(),
  },
  (t) => [index("accounts_user_id_idx").on(t.userId)],
);

export const verifications = pgTable(
  "verifications",
  {
    id: id(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: instant().notNull(),
    ...timestamps(),
  },
  (t) => [index("verifications_identifier_idx").on(t.identifier)],
);

export const rateLimits = pgTable("rate_limits", {
  id: id(),
  key: text().notNull().unique(),
  count: integer().notNull(),
  lastRequest: bigint({ mode: "number" }).notNull(),
  ...timestamps(),
});

// ---------------------------------------------------------------------------
// App

export const calendarStatus = pgEnum("calendar_status", CALENDAR_STATUSES);
export const pieceStatus = pgEnum("piece_status", PIECE_STATUSES);
export const calendarEventType = pgEnum(
  "calendar_event_type",
  CALENDAR_EVENT_TYPES,
);

export const clients = pgTable(
  "clients",
  {
    id: id(),
    userId: uuid()
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    name: text().notNull(),
    industry: text(),
    contactName: text(),
    contactPhone: text(),
    // Network codes from src/domain/catalog.ts.
    networks: text()
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    approvalNotes: text(),
    notes: text(),
    // "Cliente desde": first day of the month. See docs/DECISIONES.md.
    clientSince: date({ mode: "string" }),
    archivedAt: instant(),
    ...timestamps(),
  },
  (t) => [
    index("clients_user_id_idx").on(t.userId),
    check("clients_name_not_blank", sql`btrim(${t.name}) <> ''`),
    check(
      "clients_client_since_first_day",
      sql`extract(day from ${t.clientSince}) = 1`,
    ),
  ],
);

export const calendars = pgTable(
  "calendars",
  {
    id: id(),
    clientId: uuid()
      .notNull()
      .references(() => clients.id, { onDelete: "restrict" }),
    // Always the first day of the month.
    month: date({ mode: "string" }).notNull(),
    status: calendarStatus().notNull().default("draft"),
    sentAt: instant(),
    approvedAt: instant(),
    ...timestamps(),
  },
  (t) => [
    unique("calendars_client_id_month_key").on(t.clientId, t.month),
    check("calendars_month_first_day", sql`extract(day from ${t.month}) = 1`),
    check(
      "calendars_status_dates",
      sql`case ${t.status}
        when 'draft' then ${t.sentAt} is null and ${t.approvedAt} is null
        when 'sent' then ${t.sentAt} is not null and ${t.approvedAt} is null
        when 'approved' then ${t.sentAt} is not null and ${t.approvedAt} is not null
      end`,
    ),
  ],
);

export const pieces = pgTable(
  "pieces",
  {
    id: id(),
    calendarId: uuid()
      .notNull()
      .references(() => calendars.id, { onDelete: "cascade" }),
    // Publication day, inside the calendar's month (checked by the server).
    date: date({ mode: "string" }).notNull(),
    // Codes from src/domain/catalog.ts, validated by the server.
    network: text().notNull(),
    format: text().notNull(),
    topic: text().notNull(),
    idea: text(),
    status: pieceStatus().notNull().default("pending"),
    doneAt: instant(),
    deliveredAt: instant(),
    assetUrl: text(),
    // Optional label for the link. See docs/DECISIONES.md.
    assetName: text(),
    ...timestamps(),
  },
  (t) => [
    index("pieces_calendar_id_date_idx").on(t.calendarId, t.date),
    check(
      "pieces_topic_length",
      sql`char_length(btrim(${t.topic})) between 1 and 120`,
    ),
    check("pieces_idea_length", sql`char_length(${t.idea}) <= 2000`),
    check("pieces_asset_url_scheme", sql`${t.assetUrl} ~* '^https?://'`),
    check(
      "pieces_asset_name",
      sql`${t.assetName} is null or (${t.assetUrl} is not null and char_length(${t.assetName}) <= 200)`,
    ),
    check(
      "pieces_status_dates",
      sql`case ${t.status}
        when 'pending' then ${t.doneAt} is null and ${t.deliveredAt} is null
        when 'done' then ${t.doneAt} is not null and ${t.deliveredAt} is null
        when 'delivered' then ${t.doneAt} is not null and ${t.deliveredAt} is not null
      end`,
    ),
  ],
);

/** A piece as it was when the client approved the calendar. */
export type PieceSnapshot = {
  id: string;
  date: string;
  network: string;
  format: string;
  topic: string;
  idea: string | null;
  status: PieceStatus;
};

export const calendarEvents = pgTable(
  "calendar_events",
  {
    id: id(),
    calendarId: uuid()
      .notNull()
      .references(() => calendars.id, { onDelete: "cascade" }),
    type: calendarEventType().notNull(),
    // Only on `approved`: what the client approved.
    snapshot: jsonb().$type<PieceSnapshot[]>(),
    ...timestamps(),
  },
  (t) => [
    index("calendar_events_calendar_id_created_at_idx").on(
      t.calendarId,
      t.createdAt,
    ),
    check(
      "calendar_events_snapshot_on_approval",
      sql`(${t.type} = 'approved') = (${t.snapshot} is not null)`,
    ),
  ],
);
